import "@/app/globals.css";
import AppWalletProvider from "@/components/AppWalletProvider";
import LogoFull from "@/components/LogoFull";
import Spinner from "@/components/Spinner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Remixers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWalletProvider>
          <Spinner />
          <header className="flex justify-center py-4">
            <LogoFull height={60} />
          </header>
          <main>{children}</main>
        </AppWalletProvider>
      </body>
    </html>
  );
}
