import AppWalletProvider from "@/components/AppWalletProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Remixers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWalletProvider>
          <header>
            <div className="text-3xl font-bold">Remixers</div>
          </header>
          <main>{children}</main>
        </AppWalletProvider>
      </body>
    </html>
  );
}
